package:
  name: recbole
  version: 0.1.1

source:
  path: ../

requirements:
  build:
    - python
  host:
    - python
    - numpy >=1.17.2
    - scipy >=1.3.1
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - matplotlib >=3.1.3
    - scikit-learn >=0.23.2
    - pytorch
  run:
    - python
    - numpy >=1.17.2
    - scipy >=1.3.1
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - matplotlib >=3.1.3
    - scikit-learn >=0.23.2
    - pytorch

test:
  imports:
    - recbole

about:
  home: https://recbole.io/
  license: MIT
  summary: "A unified, comprehensive and efficient recommendation library"